source 'http://github.intra.douban.com/iOS/CocoaPodsSpecs.git'

use_frameworks!

target 'Rexxar_Example' do
  pod 'Rexxar',           :path => '../'
  pod 'MTURLProtocol',    :git => 'https://github.intra.douban.com/ios/mturlprotocol', :commit => 'd8c73d9c03703745ea5440a1c48616cc55c77d22'

  target 'Rexxar_Tests' do
    inherit! :search_paths


  end
end
