source 'http://github.intra.douban.com/iOS/CocoaPodsSpecs.git'

use_frameworks!

target 'Rexxar_Example' do
  pod 'Rexxar',           :path => '../'
  pod 'MTURLProtocol',    :git => 'https://github.intra.douban.com/ios/mturlprotocol', :commit => 'bc31853b12eee3e826eb21559ce0bf2a8bbe906c'

  target 'Rexxar_Tests' do
    inherit! :search_paths


  end
end
