source 'http://github.intra.douban.com/iOS/CocoaPodsSpecs.git'

use_frameworks!

target 'Rexxar_Example' do
  pod 'Rexxar',           :path => '../'
  pod 'MTURLProtocol',    :git => 'https://github.intra.douban.com/ios/mturlprotocol', :commit => '843cf464c86a3c9b1150c3f68831b8d48d787af5'

  target 'Rexxar_Tests' do
    inherit! :search_paths


  end
end
